

#dir configs
pickle_dir: /Users/j9/Desktop/metadata-mgmt-tool/pickled/
log_dir: /Users/j9/Desktop/metadata-mgmt-tool/logs/
config_dir: /Users/j9/Desktop/metadata-mgmt-tool/configs/
pickle_data_dir: /Users/j9/Desktop/metadata-mgmt-tool/pickled/datasets/
wkbk_uploads_dir: /Users/j9/Desktop/metadata-mgmt-tool/wkbk_uploads/


#other yaml configs
socrata_client_config_fname: socrata_config.yaml
metadataset_config: metadatasets.yaml
email_config_file: email_config_gmail.yaml


#file names
exception_logfile: grab_asset_field_defs_exception_log.txt
output_json_fn: asset_field_defs.json


#socrata specific configs
row_id_field: row_id
src_records_cnt_field: SrcRecordsCnt
dataset_records_cnt_field: DatasetRecordsCnt
fourXFour: fourXFour
isLoaded: isLoaded
datasets_to_load_fn: datasets_to_load.csv
dataset_name_field: Socrata Dataset Name
dataset_src_dir_field:  Dataset_Source_Dir
dataset_src_fn_field: Dataset Source Filename
base_url: data.sfgov.org
job_name: Update Master Data Dictionary with Existing Portal Definitions

#other stuff
json_key: updt_fields
app_name: Grab Existing Portal Field Definitions




