inputDataDir: /Users/j9/Desktop/fetch-metadata-fields/output/
inputConfigDir: /Users/j9/Desktop/fetch-metadata-fields/configs/
config_dir:  /Users/j9/Desktop/fetch-metadata-fields/configs/
socrata_client_config_fname: socrata_config.yaml
log_dir: /Users/j9/Desktop/fetch-metadata-fields/logs/
exception_logfile: master_dd_exception.log
app_name: master_data_dictionary
src_records_cnt_field: SrcRecordsCnt
dataset_records_cnt_field: DatasetRecordsCnt
fourXFour: fourXFour
row_id_field: row_id
isLoaded: isLoaded
datasets_to_load_fn: datasets_to_load_desktop.csv
dataset_name_field: Socrata Dataset Name
dataset_src_dir_field:  Dataset_Source_Dir
dataset_src_fn_field: Dataset Source Filename
base_url: data.sfgov.org
email_config_file: email_config_gmail.yaml
tables:
  global_fields:
    fbf: ctmu-r9d9
    field_list: ['global_string', 'field_name']
  dataset_inventory:
    fbf: y8fp-fbf5
    field_list: ['inventory_id', 'department_or_division', 'dataset_id']
    field_mapping: {'dataset_id': 'datasetid', 'inventory_id': 'inventoryid', 'department_or_division': 'department_from_inventory'}
  asset_fields:
    fbf: skzx-6gkn
    field_list: ['columnid', 'systemid', 'dataset_name','department', 'field_name', 'field_type', 'field_render_type', 'field_api_name','field_description','data_type', 'childview', 'rowsupdatedat', 'createdat']
    field_mapping: {'systemid': 'datasetid', 'department':'department_from_catalog', 'field_type': 'socrata_field_type', 'field_render_type': 'field_type', 'field_api_name': 'api_key',  'field_description':'field_definition', 'childview': 'nbeid_geo', 'rowsupdatedat':'last_updt_dt_data', 'createdat': 'created_date'}
  asset_inventory:
    fbf: 6u88-vc79
    field_list: ['data_steward_email', 'u_id',  'data_steward_name', 'type']
    field_mapping: {'u_id': 'datasetid', 'data_steward_email': 'data_steward', }
  data_dictionary_attachments:
    fbf: a2hm-yzs6
    field_list: ['attachment_url', 'dataset_id', 'data_dictionary_attached']
    field_mapping: {'dataset_id': 'datasetid'}
  data_dictionary_do_not_process:
    fbf: a2mb-xwnt
    field_list: ['departments', 'stewards']
  cordinators:
    fbf: e5db-hccr
    field_list: ['email', 'department', 'primary']
    field_mapping: {'email': 'data_coordinator'}
  department_lookup:
    fbf: n66m-42dh
    field_list: ['department_string', 'department_transform']
  global_field_defs:
    fbf: iwpj-u2p9
    field_list: ['global_field_name', 'global_field_definition']

master_data_dictionary:
    fourXFour: 8zp7-ik63
    #fourXFour: asfx-iyhm
    Socrata Dataset Name: Master Data Dictionary
    row_id: columnid


job_name: Update Master Data Dictionary

fields_to_include: ['columnid', 'datasetid', 'dataset_name', 'inventoryid', 'field_name', 'socrata_field_type', 'field_type', 'api_key', 'data_steward', 'data_steward_name', 'department_from_inventory', 'department_from_catalog', 'data_coordinator', 'data_dictionary_attached', 'attachment_url']
fields_calculate: ['department', 'field_documented', 'global_field', 'do_not_process', 'field_definition', 'open_data_portal_url']
fields_to_exclude: ['field_alias', 'field_type_flag', 'status', 'date_last_changed']
